### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rene-dev** [STMBL/QtServoterm#1]
- [x]  history
- [x]  auto refresh of ports
- [x]  triggering my magic trigger byte of 0xfe
- [x]  config editor
- [x]  xy mode
- [x]  csv output
- [x]  jogging
- [x]  file import
- [ ] remove jog checkbox, jog when right control key is pressed
- [ ] spring back slider for jog velocity control
- [ ] disable individual channels
- [ ] option for bausrate
